export interface CartItem {
    _ownerId: string,
    _id: string,
    _createdOn: number,
    image: string,
    altImages: string[],
    cat: string,
    subCat: string,
    description: string,
    brand: string,
    size: (string | number)[],
    selectedSize: string | number,
    color: string[],
    selectedColor: string,
    quantity: number,
    selectedQuantity: number,
    price: number,
    buyed: boolean,
    product: number,
    checked: boolean
}

export const cartItemInitailState = {
    _ownerId: '',
    _id: '',
    _createdOn: NaN,
    image: '',
    altImages: [],
    cat: '',
    subCat: '',
    description: '',
    brand: '',
    size: [],
    selectedSize: '',
    color: [],
    selectedColor: '',
    quantity: NaN,
    selectedQuantity: NaN,
    price: NaN,
    buyed: true,
    product: NaN,
    checked: false
}