export interface CartItem {
    _ownerId: string,
    _id: string,
    _createdOn: number,
    image: string,
    altImages: string[],
    cat: string,
    subCat: string,
    description: string,
    brand: string,
    size: (string | number)[],
    selectedSize: string | number,
    color: string[],
    selectedColor: string,
    quantity: number,
    selectedQuantity: number,
    price: number,
    buyed?: boolean,
    product: number,
    checked: boolean
}